#!/usr/bin/env bash
javac -d CODE/IDE_PROJET_LAVALLEE_TANGUY_CIAVALDINI_MARZOUK/bin CODE/IDE_PROJET_LAVALLEE_TANGUY_CIAVALDINI_MARZOUK/src/*.java
java -cp CODE/IDE_PROJET_LAVALLEE_TANGUY_CIAVALDINI_MARZOUK/bin Main DB
